### PR TITLE
Add Ruby 3.3(.0) and drop obsolete patch versions.

### LINKED ISSUE #62: Ruby 3.3 support
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/

~Looks like we [might need to start building yjit](https://www.github.com/rails/rails/pull/49947) 🦀🦀🦀 (fair enough, we've put it off for quite some time and apparently the RAM tradeoff is less awful than it used to be).~ Nah it's [still optional](https://github.com/rails/rails/blob/a409c63/railties/lib/rails/generators/rails/app/templates/config/initializers/enable_yjit.rb.tt) even for projects that pull in the new initializer. 🥾🥫🛣️ #65

### PR DESCRIPTION
**Pull request by sengi**
Fixes #62.

No YJIT support yet; that's tracked in #65.

Tested: builds locally.

### CODE REVIEW

**Review by theseanything — APPROVED** [review]
🚀

**Review by samsimpson1 — APPROVED** [review]
This version list will need updating too: https://github.com/alphagov/govuk-ruby-images/blob/main/.github/workflows/sign.yaml#L16

**Review by dj-maisy — APPROVED** [review]
👍

**Comment by sengi** [comment]
> This version list will need updating too: https://github.com/alphagov/govuk-ruby-images/blob/main/.github/workflows/sign.yaml#L16

Ah thanks!

**Comment by sengi** [comment]
https://github.com/alphagov/govuk_app_config/issues/341 is likely a blocker for pretty much all GOV.UK projects looking to update to Ruby 3.3.

**Pull request merged**
